const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#000',
    background: '#fff',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    cardBackground: '#fff',
    inputBackground: '#fff',
    inputBorder: '#e0e0e0',
    buttonBackground: '#2196F3',
    buttonText: '#fff',
    warningBackground: '#FFF3E0',
    warningText: '#E65100',
    warningBorder: '#FF9800',
    disabledText: '#999',
    disabledBackground: '#f5f5f5',
    switchInactive: '#e0e0e0',
    switchActive: '#2196F3',
    switchThumb: '#fff',
    shadowColor: '#000',
  },
  dark: {
    text: '#fff',
    background: '#000',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    cardBackground: '#1c1c1e',
    inputBackground: '#2c2c2e',
    inputBorder: '#3c3c3e',
    buttonBackground: '#2196F3',
    buttonText: '#fff',
    warningBackground: '#2c2c2e',
    warningText: '#ff6b35',
    warningBorder: '#ff6b35',
    disabledText: '#666',
    disabledBackground: '#1c1c1e',
    switchInactive: '#3c3c3e',
    switchActive: '#2196F3',
    switchThumb: '#fff',
    shadowColor: '#fff',
  },
};
